// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEw4p767xELtq5J8L_16PYCFOvpgYgfz8',
    appId: '1:1013568067759:web:db96ca25df95cc8b39dc5a',
    messagingSenderId: '1013568067759',
    projectId: 'campuseats-73325',
    authDomain: 'campuseats-73325.firebaseapp.com',
    storageBucket: 'campuseats-73325.firebasestorage.app',
    measurementId: 'G-2LBBWV4GHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL6uzo1X6P6jdU_BerfLrZXxVGndZWrNM',
    appId: '1:1013568067759:android:134003dc8c142f3739dc5a',
    messagingSenderId: '1013568067759',
    projectId: 'campuseats-73325',
    storageBucket: 'campuseats-73325.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdjERYKdT9FiYgCPIw4aK_gDS_2-2VWmA',
    appId: '1:1013568067759:ios:5691660d2ff4b1a439dc5a',
    messagingSenderId: '1013568067759',
    projectId: 'campuseats-73325',
    storageBucket: 'campuseats-73325.firebasestorage.app',
    iosBundleId: 'com.example.campuseats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdjERYKdT9FiYgCPIw4aK_gDS_2-2VWmA',
    appId: '1:1013568067759:ios:5691660d2ff4b1a439dc5a',
    messagingSenderId: '1013568067759',
    projectId: 'campuseats-73325',
    storageBucket: 'campuseats-73325.firebasestorage.app',
    iosBundleId: 'com.example.campuseats',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEw4p767xELtq5J8L_16PYCFOvpgYgfz8',
    appId: '1:1013568067759:web:daf8fd7da4db330739dc5a',
    messagingSenderId: '1013568067759',
    projectId: 'campuseats-73325',
    authDomain: 'campuseats-73325.firebaseapp.com',
    storageBucket: 'campuseats-73325.firebasestorage.app',
    measurementId: 'G-X9Z7R0V3E7',
  );
}



